---
# This tasks create a security group {{tag_prefix}}castle-gate
- name: Create 'castle-gate' security group
  local_action:
     module: ec2_group
     name: "{{tag_prefix}}{{castle_gate_name}}"
     description: "Web facing services"
     region: "{{aws_region}}"
     rules:
       - proto: tcp
         type: http
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         type: http
         from_port: 443
         to_port: 443
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         type: ssh
         from_port: 22
         to_port: 22
         group_name: "{{tag_prefix}}{{kitchen_door_name}}"
     rules_egress:
       - proto: all
         type: all
         cidr_ip: 0.0.0.0/0
