---
- name: Get instance id
  local_action:
    module: shell /python/ansible/bin/list_instances -r ap-southeast-2 -H ID,T:Name -t | grep Front | awk '{print $1}'
    register: instance_id


- name: Terminate {{ec2_id}} instance in {{aws_region}}
  local_action:
    module: ec2
    region: '{{aws_region}}'
    count_tag:
      prefix: "{{ tag_prefix}}archi"
    state: 'running'

