---
# This playbook contains play that 
- name: Import key pair to connect to EC2 instances
  local_action:
    module: ec2_key
    name: "{{key_name}}"
    region: "{{aws_region}}"
    key_material: "{{item}}"
  with_file: ~/.ssh/{{key_name}}.pub
