---
- name: Delete 'kitchen-entrance' security group
  local_action:
    module: ec2_group
    name: "{{tag_prefix}}kitchen-door"
    description: "Monitoring services"
    region: "{{aws_region}}"
    state: absent
