---
- name: Delete 'vault' security group
  local_action:
    module: ec2_group
    name: "{{tag_prefix}}{{vault_name}}"
    description: "Email services"
    region: "{{aws_region}}"
    state: absent
