---
- name: Delete 'watch-tower' security group
  local_action:
    module: ec2_group
    name: "{{tag_prefix}}watch-tower"
    description: "Email services"
    region: "{{aws_region}}"
    state: absent
