---
- name: Create front-end web server EC2 instances
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{castle_gate_name}}"
    instance_type: "{{instance_type}}"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: 8
        delete_on_termination: true
    wait: yes
    user_data: "{{ lookup('template', '../templates/castle-gate-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{ tag_prefix }}archi"
  register: front_end_servers

- name: set private_ip 
  set_fact: 
    private_ip: "{{item.private_ip}}"
  with_items: front_end_servers.instances


- name: Update template file
  local_action: 
    module: copy
    content: "{{ lookup('template', '../templates/web-change-record-set.j2')}}"
    dest: ./web-change-record-set.json
    

- name: Registration of castle-gate(web) in DNS
  local_action:
    module: command
      aws route53 change-resource-record-sets --hosted-zone-id "{{hosted_zone_id}}" --change-batch file://web-change-record-set.json
