---
- name: Create monitoring EC2 instances
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{kitchen_door_name}}"
    instance_type: "{{instance_type}}"
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    instance_profile_name: "{{tag_prefix}}kitchen-door-profile"
    volumes:
      - device_name: /dev/sda1
        volume_size: 8
        delete_on_termination: true
    wait: yes
    user_data: "{{ lookup('template', '../templates/kitchen-door-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{ tag_prefix }}archi"
  register: devel_servers
- debug: msg="{{devel_servers}}"
