---
- name: Update default VPC atributes enable-dns-support
  local_action:
    module: command
      aws ec2 modify-vpc-attribute --vpc-id {{vpc_id}} --enable-dns-support "{\"Value\":true}" --region {{aws_region}}


- name: Update default VPC atributes enable-dns-hostnames
  local_action:
    module: command
      aws ec2 modify-vpc-attribute --vpc-id {{vpc_id}} --enable-dns-hostnames "{\"Value\":true}" --region {{aws_region}}

- name: Create hosted-zone
  local_action:
    module: command
      aws route53 create-hosted-zone --name {{internal_domain}}  --caller-reference {{request_id}} --hosted-zone-config "Comment=DnsConfig"
  register: hosted_zone


- debug: msg="{{hosted_zone}}"
