# We cannot attach EBS encrypted volumes to all instance types
# References:
#  - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
#  - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_supported_instances
- name: Create databases EC2 instances
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "{{tag_prefix}}{{vault_name}}"
    instance_profile_name: "{{tag_prefix}}{{vault_name}}-profile"
    instance_type: m3.medium
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    wait: yes
    user_data: "{{ lookup('template', '../templates/vault-cloud-init-script.j2') }}"
    instance_tags:
      prefix: "{{ tag_prefix }}archi"
  register: db_server

- name: Create Encrypted EBS volume
  local_action:
    module: ec2_vol
    device_name: /dev/sdf
    encrypted: yes
    instance: "{{db_server.instance_ids}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    volume_size: 20
    volume_type: gp2

- name: set private_ip 
  set_fact: 
    private_ip: "{{item.private_ip}}"
  with_items: db_server.instances


- name: Update template file
  local_action: 
    module: copy
    content: "{{ lookup('template', '../templates/db-change-record-set.j2')}}"
    dest: ./db-change-record-set.json
    

- name: Registration of vault in DNS
  local_action:
    module: command
      aws route53 change-resource-record-sets --hosted-zone-id "{{hosted_zone_id}}" --change-batch file://db-change-record-set.json
