---
# This playbook deletes all ec2 instances
#
# USE WITH CARE!

- name: Delete devel EC2 instances
#  hosts: security_group_kitchen_door
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
   - deleteinstances
