# XXX Until Ansible v2 is widely available:
# We run all native Ansible commands before awscli commands because those
# later could fail if the resources do not exist.

- name: Deleting groups and roles
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - deletegroups
    - deletes3bucket
    - deleteiamroles
    - deleteprivatedns

