---
# This playbook configures machines used for code deployment and monitoring

- name: Configure machines used for code deployment and monitoring
  hosts: security_group_kitchen_door
  gather_facts: False
  sudo: yes
  sudo_user: root

  roles:
    - warmup
    - backstage
