---
# This playbook configures machines used for email services.

- name: Configure machines machines used for email services.
  hosts: security_group_watch_tower
  gather_facts: False
  sudo: yes
  sudo_user: root

  roles:
    - warmup
    - mailfront
