---
# This playbook configures machines used for web services (behind session)

- name: Configure machines machines used for web services
  hosts: security_group_courtyard
  gather_facts: False
  sudo: yes
  sudo_user: root

  roles:
    - warmup
    - worker
